"""revision2

Revision ID: 057d929c6a82
Revises: b4ee7512f532
Create Date: 2024-03-25 14:24:50.128044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057d929c6a82'
down_revision = 'b4ee7512f532'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('description', sa.String(), nullable=True))
    op.add_column('education', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('education', 'institute',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('education', 'degree',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'degree',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('education', 'institute',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('education', 'location')
    op.drop_column('education', 'description')
    # ### end Alembic commands ###
