"""revi

Revision ID: ffb7edee8a7e
Revises: 9dea95c094bb
Create Date: 2024-03-24 17:25:43.955739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb7edee8a7e'
down_revision = '9dea95c094bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributors', 'phone_number')
    # ### end Alembic commands ###
